/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.lang.Math;        
/**
 *
 * @author 01ele
 */
public class Calculations extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Calculations() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        mathApp = new javax.swing.JTabbedPane();
        loanPanel = new javax.swing.JPanel();
        loanCalcButton = new java.awt.Button();
        pField = new java.awt.TextField();
        label6 = new java.awt.Label();
        aprLoanField = new java.awt.TextField();
        label7 = new java.awt.Label();
        nLoanField = new java.awt.TextField();
        label8 = new java.awt.Label();
        yearLoanField = new java.awt.TextField();
        label9 = new java.awt.Label();
        monthLoanField = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        label15 = new java.awt.Label();
        totalLoanField = new java.awt.TextField();
        label16 = new java.awt.Label();
        savingsPanel = new javax.swing.JPanel();
        savingPlanCalcButton = new java.awt.Button();
        aField = new java.awt.TextField();
        label2 = new java.awt.Label();
        aprField = new java.awt.TextField();
        label3 = new java.awt.Label();
        nField = new java.awt.TextField();
        label4 = new java.awt.Label();
        yearField = new java.awt.TextField();
        label5 = new java.awt.Label();
        answerField = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();
        absoRelPanel = new javax.swing.JPanel();
        abRelDifButton = new java.awt.Button();
        comVal = new java.awt.TextField();
        label10 = new java.awt.Label();
        relVal = new java.awt.TextField();
        label11 = new java.awt.Label();
        relDiffDecimal = new java.awt.TextField();
        label12 = new java.awt.Label();
        absoDiffMoney = new java.awt.TextField();
        label13 = new java.awt.Label();
        relDiffPercentage = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();
        label14 = new java.awt.Label();
        compoundPanel = new javax.swing.JPanel();
        compButton = new java.awt.Button();
        pCompound = new java.awt.TextField();
        label17 = new java.awt.Label();
        aprCompound = new java.awt.TextField();
        label18 = new java.awt.Label();
        yCompound = new java.awt.TextField();
        label20 = new java.awt.Label();
        compoundAnswer = new java.awt.TextField();
        jLabel4 = new javax.swing.JLabel();
        compoundMultiPanel = new javax.swing.JPanel();
        compMultiButton = new java.awt.Button();
        pCompoundMulti = new java.awt.TextField();
        label19 = new java.awt.Label();
        aprCompoundMulti = new java.awt.TextField();
        label21 = new java.awt.Label();
        nCompoundMulti = new java.awt.TextField();
        label22 = new java.awt.Label();
        compoundMultiAnswer = new java.awt.TextField();
        jLabel5 = new javax.swing.JLabel();
        yCompoundMulti = new java.awt.TextField();
        label23 = new java.awt.Label();
        continuousCompoundPanel = new javax.swing.JPanel();
        contCompButton = new java.awt.Button();
        pContCompound = new java.awt.TextField();
        label24 = new java.awt.Label();
        aprContCompound = new java.awt.TextField();
        label25 = new java.awt.Label();
        yContCompound = new java.awt.TextField();
        label26 = new java.awt.Label();
        contCompoundAnswer = new java.awt.TextField();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mathApp.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        loanCalcButton.setLabel("Calculate");
        loanCalcButton.setName(""); // NOI18N
        loanCalcButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loanCalcButtonMouseClicked(evt);
            }
        });

        label6.setText("Starting Principal (P)");

        label7.setText("Annual Percentage Rate (APR)");

        label8.setText("Number of Payment Periods Per Year (n)");

        label9.setText("Loan Term in Years (Y)");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoanPay.jpg"))); // NOI18N

        label15.setText("Monthly Payment ($)");

        label16.setText("Total Payment ($)");

        javax.swing.GroupLayout loanPanelLayout = new javax.swing.GroupLayout(loanPanel);
        loanPanel.setLayout(loanPanelLayout);
        loanPanelLayout.setHorizontalGroup(
            loanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loanPanelLayout.createSequentialGroup()
                        .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(loanPanelLayout.createSequentialGroup()
                            .addComponent(aprLoanField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(loanPanelLayout.createSequentialGroup()
                            .addComponent(nLoanField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(loanPanelLayout.createSequentialGroup()
                            .addComponent(pField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(loanPanelLayout.createSequentialGroup()
                            .addGroup(loanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(yearLoanField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(loanPanelLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(loanCalcButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(loanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(loanPanelLayout.createSequentialGroup()
                                    .addComponent(monthLoanField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totalLoanField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
        );
        loanPanelLayout.setVerticalGroup(
            loanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loanPanelLayout.createSequentialGroup()
                        .addGroup(loanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(loanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(aprLoanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(loanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nLoanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(loanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yearLoanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(loanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(monthLoanField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loanCalcButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalLoanField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loanPanelLayout.createSequentialGroup()
                        .addComponent(label15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(13, 13, 13))
                    .addGroup(loanPanelLayout.createSequentialGroup()
                        .addComponent(label16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        mathApp.addTab("Loan Payment", loanPanel);

        savingPlanCalcButton.setLabel("Payment");
        savingPlanCalcButton.setName(""); // NOI18N
        savingPlanCalcButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                savingPlanCalcButtonMouseClicked(evt);
            }
        });

        label2.setText("Starting Principal (A)");

        label3.setText("Annual Percentage Rate (APR)");

        label4.setText("Number of Payment Periods Per Year (n)");

        label5.setText("Loan Term in Years (Y)");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SavePay.JPG"))); // NOI18N

        javax.swing.GroupLayout savingsPanelLayout = new javax.swing.GroupLayout(savingsPanel);
        savingsPanel.setLayout(savingsPanelLayout);
        savingsPanelLayout.setHorizontalGroup(
            savingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(savingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(savingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(savingsPanelLayout.createSequentialGroup()
                        .addComponent(aprField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(savingsPanelLayout.createSequentialGroup()
                        .addComponent(nField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(savingsPanelLayout.createSequentialGroup()
                        .addComponent(aField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(savingsPanelLayout.createSequentialGroup()
                        .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(savingsPanelLayout.createSequentialGroup()
                        .addComponent(answerField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(savingPlanCalcButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addContainerGap())
        );
        savingsPanelLayout.setVerticalGroup(
            savingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(savingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(savingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(savingsPanelLayout.createSequentialGroup()
                        .addGroup(savingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(aField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(savingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(aprField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(savingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(savingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(savingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(answerField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(savingPlanCalcButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        mathApp.addTab("Savings Plan Formula", savingsPanel);

        abRelDifButton.setLabel("Calculate");
        abRelDifButton.setName(""); // NOI18N
        abRelDifButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abRelDifButtonMouseClicked(evt);
            }
        });

        label10.setText("Compared Value (c)");

        label11.setText("Relative Value (r)");

        label12.setAlignment(java.awt.Label.CENTER);
        label12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label12.setText("Absolute Difference ($)");

        label13.setText("Relative Difference (Dec)");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AbsoRel.JPG"))); // NOI18N

        label14.setAlignment(java.awt.Label.CENTER);
        label14.setText("Relative Difference (%)");

        javax.swing.GroupLayout absoRelPanelLayout = new javax.swing.GroupLayout(absoRelPanel);
        absoRelPanel.setLayout(absoRelPanelLayout);
        absoRelPanelLayout.setHorizontalGroup(
            absoRelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(absoRelPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(absoRelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(absoRelPanelLayout.createSequentialGroup()
                        .addComponent(comVal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(absoRelPanelLayout.createSequentialGroup()
                        .addComponent(relVal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(absoRelPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(abRelDifButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(absoRelPanelLayout.createSequentialGroup()
                        .addGroup(absoRelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(absoDiffMoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(absoRelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(relDiffDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(absoRelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(absoRelPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, absoRelPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(relDiffPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel3))
        );
        absoRelPanelLayout.setVerticalGroup(
            absoRelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(absoRelPanelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(absoRelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(absoRelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(relVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(abRelDifButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(absoRelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(absoDiffMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(relDiffDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(absoRelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label12, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(label13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(absoRelPanelLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(relDiffPercentage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(absoRelPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mathApp.addTab("Absolute and Relative Difference", absoRelPanel);

        compButton.setLabel("Calculate");
        compButton.setName(""); // NOI18N
        compButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                compButtonMouseClicked(evt);
            }
        });

        label17.setText("Starting Principal (P)");

        label18.setText("Annual Percentage Rate (APR)");

        label20.setText("Number of Years (Y)");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Compound.JPG"))); // NOI18N

        javax.swing.GroupLayout compoundPanelLayout = new javax.swing.GroupLayout(compoundPanel);
        compoundPanel.setLayout(compoundPanelLayout);
        compoundPanelLayout.setHorizontalGroup(
            compoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(compoundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(compoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(compoundPanelLayout.createSequentialGroup()
                        .addComponent(aprCompound, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(compoundPanelLayout.createSequentialGroup()
                        .addComponent(yCompound, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(compoundPanelLayout.createSequentialGroup()
                        .addComponent(pCompound, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(compoundPanelLayout.createSequentialGroup()
                        .addComponent(compoundAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(compButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addContainerGap())
        );
        compoundPanelLayout.setVerticalGroup(
            compoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(compoundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(compoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(compoundPanelLayout.createSequentialGroup()
                        .addGroup(compoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pCompound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(compoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(aprCompound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(compoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label20, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                            .addComponent(yCompound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(compoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(compoundAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(compButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        mathApp.addTab("Compound Interest", compoundPanel);

        compMultiButton.setLabel("Calculate");
        compMultiButton.setName(""); // NOI18N
        compMultiButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                compMultiButtonMouseClicked(evt);
            }
        });

        label19.setText("Starting Principal (P)");

        label21.setText("Annual Percentage Rate (APR)");

        label22.setText("Number of Payments Per Year (n)");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CompMulti.JPG"))); // NOI18N

        label23.setText("Number of Years (Y)");

        javax.swing.GroupLayout compoundMultiPanelLayout = new javax.swing.GroupLayout(compoundMultiPanel);
        compoundMultiPanel.setLayout(compoundMultiPanelLayout);
        compoundMultiPanelLayout.setHorizontalGroup(
            compoundMultiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(compoundMultiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(compoundMultiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(compoundMultiPanelLayout.createSequentialGroup()
                        .addComponent(aprCompoundMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(compoundMultiPanelLayout.createSequentialGroup()
                        .addComponent(pCompoundMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(compoundMultiPanelLayout.createSequentialGroup()
                        .addGroup(compoundMultiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nCompoundMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(compoundMultiAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(compoundMultiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(compMultiButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(compoundMultiPanelLayout.createSequentialGroup()
                        .addComponent(yCompoundMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addContainerGap())
        );
        compoundMultiPanelLayout.setVerticalGroup(
            compoundMultiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(compoundMultiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(compoundMultiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(compoundMultiPanelLayout.createSequentialGroup()
                        .addGroup(compoundMultiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pCompoundMulti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(compoundMultiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(aprCompoundMulti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(compoundMultiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label22, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                            .addComponent(nCompoundMulti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(compoundMultiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yCompoundMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(compoundMultiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(compoundMultiAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(compMultiButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        mathApp.addTab("Compound Interest Multiple Deposits", compoundMultiPanel);

        contCompButton.setLabel("Calculate");
        contCompButton.setName(""); // NOI18N
        contCompButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contCompButtonMouseClicked(evt);
            }
        });

        label24.setText("Starting Principal (P)");

        label25.setText("Annual Percentage Rate (APR)");

        label26.setText("Number of Years (Y)");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ContCompound.JPG"))); // NOI18N

        javax.swing.GroupLayout continuousCompoundPanelLayout = new javax.swing.GroupLayout(continuousCompoundPanel);
        continuousCompoundPanel.setLayout(continuousCompoundPanelLayout);
        continuousCompoundPanelLayout.setHorizontalGroup(
            continuousCompoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(continuousCompoundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(continuousCompoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(continuousCompoundPanelLayout.createSequentialGroup()
                        .addComponent(aprContCompound, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(continuousCompoundPanelLayout.createSequentialGroup()
                        .addComponent(yContCompound, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(continuousCompoundPanelLayout.createSequentialGroup()
                        .addComponent(pContCompound, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(continuousCompoundPanelLayout.createSequentialGroup()
                        .addComponent(contCompoundAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contCompButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addContainerGap())
        );
        continuousCompoundPanelLayout.setVerticalGroup(
            continuousCompoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(continuousCompoundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(continuousCompoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(continuousCompoundPanelLayout.createSequentialGroup()
                        .addGroup(continuousCompoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pContCompound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(label24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(continuousCompoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(aprContCompound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(continuousCompoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label26, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                            .addComponent(yContCompound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(continuousCompoundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contCompoundAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contCompButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        mathApp.addTab("Continuous Compounding Interest", continuousCompoundPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mathApp)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mathApp)
                .addGap(0, 0, 0))
        );

        mathApp.getAccessibleContext().setAccessibleName("Compound Interest");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savingPlanCalcButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savingPlanCalcButtonMouseClicked
        // Variables for user inputs used in Savings Plan Calculations
        try{
            double pmt = 0;
            double a = Double.parseDouble(aField.getText());
            double apr = Double.parseDouble(aprField.getText().replace("%", ""));
            double n = Double.parseDouble(nField.getText());
            double y = Double.parseDouble(yearField.getText());
            double calcOne = 0;
            double calcTwo = 0;
            double calcThree = 0;
            double calcFour = 0;
            // Calculations
            if (apr >= 1){
                apr = apr / 100;
            }
            calcOne = a * (apr/n);
            calcTwo = 1 + (apr/n);
            calcThree = n*y;
            calcFour = ((Math.pow(calcTwo, calcThree))-1);
            pmt = calcOne / calcFour;
            // Display answer for user
            answerField.setText("$" + Double.toString(pmt));
        }
        // Give errors for improper user input
        catch(Exception e){
            String t = "Try Again";
            aField.setText(t);
            aprField.setText(t);
            nField.setText(t);
            yearField.setText(t);
        }
    }//GEN-LAST:event_savingPlanCalcButtonMouseClicked

    private void loanCalcButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanCalcButtonMouseClicked
        // Variables for user inputs used in Loan Calculations
        try{
            double p = Double.parseDouble(pField.getText());            
            double apr = Double.parseDouble(aprLoanField.getText().replace("%", ""));
            double n = Double.parseDouble(nLoanField.getText());
            double y = Double.parseDouble(yearLoanField.getText());
            double calcOne = 0.0;
            double calcTwo = 0.0;
            double calcThree = 0.0;
            double calcFour = 0.0;
            double payment = 0.0;
            double totalPayments = 0.0;
            //Calculations
            if (apr >= 1){
                apr = apr / 100;
            }
            calcOne = p * (apr / n);
            calcTwo = 1 + (apr / n);
            calcThree = (-n*y);
            calcFour = (1 - (Math.pow(calcTwo, calcThree)));
            payment = calcOne / calcFour;
            totalPayments = ((y) * (n) * (payment));
            // Display answer for user
            monthLoanField.setText("$" + Double.toString(payment));
            totalLoanField.setText("$" + Double.toString(totalPayments));
        }
        // Give errors for improper user input
        catch(Exception e){
            String t = "Try Again";
            pField.setText(t);
            aprLoanField.setText(t);
            nLoanField.setText(t);
            yearLoanField.setText(t);
            monthLoanField.setText(t);
            totalLoanField.setText(t);
        }
    }//GEN-LAST:event_loanCalcButtonMouseClicked

    private void abRelDifButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abRelDifButtonMouseClicked
        // Variables for user inputs used in Absolute and Relative Difference Calculations
        try{
            // Create variables for user inputs
            double c = Double.parseDouble(comVal.getText());
            double r = Double.parseDouble(relVal.getText());
            // Calculations
            double absoDiff = c - r;
            double relDiff = (((c-r)/r)*1.00);
            double relDiffPer = r * 100;
            // Display the results for user
            absoDiffMoney.setText("$" + Double.toString(absoDiff));
            relDiffDecimal.setText(Double.toString(relDiff));
            relDiffPercentage.setText(Double.toString(relDiffPer));
        }
        // Give errors for improper user input
        catch (Exception e){
            String t = "Try Again";
            comVal.setText(t);
            relVal.setText(t);
            absoDiffMoney.setText(t);
            relDiffDecimal.setText(t);
            relDiffPercentage.setText(t);            
        }
    }//GEN-LAST:event_abRelDifButtonMouseClicked

    private void compButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compButtonMouseClicked
        // Variables for user inputs used in Compound Interest Calculations
        try{
            double p = Double.parseDouble(pCompound.getText());
            double apr = Double.parseDouble(aprCompound.getText().replace("%", ""));
            double y = Double.parseDouble(yCompound.getText());
            double calcOne;        
            double calcTwo;
            double calcThree;
            double payment;
            // Calculations
            if (apr >= 1){
                apr = apr / 100;
            }
            calcOne = 1 + (apr);
            calcTwo = (Math.pow(calcOne, y));
            calcThree = p * calcTwo;
            payment = calcThree;
            // Answer
            compoundAnswer.setText("$" + Double.toString(payment));
        }
        // Give errors for improper user input
        catch(Exception e){
            String t = "Try Again";
            pCompound.setText(t);
            aprCompound.setText(t);
            yCompound.setText(t);
            compoundAnswer.setText(t);
        }
        
    }//GEN-LAST:event_compButtonMouseClicked

    private void compMultiButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compMultiButtonMouseClicked
        // Variables for user inputs used in Compound Interest Calculations
        try{
            double p = Double.parseDouble(pCompoundMulti.getText());
            double apr = Double.parseDouble(aprCompoundMulti.getText().replace("%", ""));
            double n = Double.parseDouble(yCompoundMulti.getText());
            double y = Double.parseDouble(yCompoundMulti.getText());
            double calcOne;        
            double calcTwo;
            double calcThree;
            double calcFour;
            double payment;
            // Calculations
            if (apr >= 1){
                apr = apr / 100;
            }
            calcOne = 1 + (apr/n);
            calcTwo = n*y;
            calcThree = (Math.pow(calcOne, calcTwo));
            calcFour = p * calcThree;
            payment = calcFour;
            // Display user results
            compoundMultiAnswer.setText("$" + Double.toString(payment));
        }
        catch(Exception e){
            
        }
        
    }//GEN-LAST:event_compMultiButtonMouseClicked

    private void contCompButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contCompButtonMouseClicked
        // Variables for user inputs used in Compound Interest Calculations
        try{
            double p = Double.parseDouble(pContCompound.getText());
            double apr = Double.parseDouble(aprContCompound.getText().replace("%", ""));
            double y = Double.parseDouble(yContCompound.getText());
            double e = 2.71828;
            double calcOne;        
            double calcTwo;
            double calcThree;
            double payment;
            // Calculations
            if (apr >= 1){
                apr = apr / 100;
            }
            calcOne = apr * y;
            calcTwo = (Math.pow(e, calcOne));
            calcThree = p * calcTwo;
            payment = calcThree;
            // Answer
            contCompoundAnswer.setText("$" + Double.toString(payment));
        }
        // Give errors for improper user input
        catch(Exception e){
            String t = "Try Again";
            pContCompound.setText(t);
            aprContCompound.setText(t);
            yContCompound.setText(t);
            contCompoundAnswer.setText(t);
        }
    }//GEN-LAST:event_contCompButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField aField;
    private java.awt.Button abRelDifButton;
    private java.awt.TextField absoDiffMoney;
    private javax.swing.JPanel absoRelPanel;
    private java.awt.TextField answerField;
    private java.awt.TextField aprCompound;
    private java.awt.TextField aprCompoundMulti;
    private java.awt.TextField aprContCompound;
    private java.awt.TextField aprField;
    private java.awt.TextField aprLoanField;
    private java.awt.TextField comVal;
    private java.awt.Button compButton;
    private java.awt.Button compMultiButton;
    private java.awt.TextField compoundAnswer;
    private java.awt.TextField compoundMultiAnswer;
    private javax.swing.JPanel compoundMultiPanel;
    private javax.swing.JPanel compoundPanel;
    private java.awt.Button contCompButton;
    private java.awt.TextField contCompoundAnswer;
    private javax.swing.JPanel continuousCompoundPanel;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label16;
    private java.awt.Label label17;
    private java.awt.Label label18;
    private java.awt.Label label19;
    private java.awt.Label label2;
    private java.awt.Label label20;
    private java.awt.Label label21;
    private java.awt.Label label22;
    private java.awt.Label label23;
    private java.awt.Label label24;
    private java.awt.Label label25;
    private java.awt.Label label26;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.Button loanCalcButton;
    private javax.swing.JPanel loanPanel;
    private javax.swing.JTabbedPane mathApp;
    private java.awt.TextField monthLoanField;
    private java.awt.TextField nCompoundMulti;
    private java.awt.TextField nField;
    private java.awt.TextField nLoanField;
    private java.awt.TextField pCompound;
    private java.awt.TextField pCompoundMulti;
    private java.awt.TextField pContCompound;
    private java.awt.TextField pField;
    private java.awt.TextField relDiffDecimal;
    private java.awt.TextField relDiffPercentage;
    private java.awt.TextField relVal;
    private java.awt.Button savingPlanCalcButton;
    private javax.swing.JPanel savingsPanel;
    private java.awt.TextField totalLoanField;
    private java.awt.TextField yCompound;
    private java.awt.TextField yCompoundMulti;
    private java.awt.TextField yContCompound;
    private java.awt.TextField yearField;
    private java.awt.TextField yearLoanField;
    // End of variables declaration//GEN-END:variables
}
